export enum MovieStatusEnum {
  POST_PRODUCTION = 'POST_PRODUCTION',
  IN_PRODUCTION = 'IN_PRODUCTION',
  CANCELED = 'CANCELED',
  RELEASED = 'RELEASED',
  PLANNED = 'PLANNED',
  RUMORED = 'RUMORED'
}
